language: generic

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - osx
  - linux
  
addons:
  apt:
    packages:
      - swi-prolog
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update            ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install swi-prolog; fi
  
### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change
